=== ikeramor/pbl_grupo_3/docs/PBL6.dtd
<!ELEMENT Analisis (Paciente+)>
<!ATTLIST Analisis modalidad CDATA #FIXED "Retinografia">
<!ELEMENT Paciente (Nombre, Apellidos, Sexo, Edad, FechaNacimiento, InformacionDeExtraccion, InformacionDeLaImagen, Diagnostico)>
<!ATTLIST Paciente id CDATA #REQUIRED>
<!ELEMENT Nombre (#PCDATA)>
<!ELEMENT Apellidos (#PCDATA)>
<!ELEMENT Sexo (#PCDATA)>
<!ELEMENT Edad (#PCDATA)>
<!ELEMENT FechaNacimiento (#PCDATA)>
<!ELEMENT InformacionDeExtraccion (Especialista, CentroDeAdquisicion, FechaDeAdquisicion)>
<!ELEMENT Especialista (#PCDATA)>
<!ELEMENT CentroDeAdquisicion (#PCDATA)>
<!ELEMENT FechaDeAdquisicion (#PCDATA)>
<!ELEMENT InformacionDeLaImagen (Bits, ResolucionDeLaImagen, Formato, TamañoMB, Imagen)>
<!ELEMENT Bits (#PCDATA)>
<!ELEMENT ResolucionDeLaImagen (anchura, altura)>
<!ELEMENT Formato (#PCDATA)>
<!ELEMENT anchura (#PCDATA)>
<!ELEMENT altura (#PCDATA)>
<!ELEMENT TamañoMB (#PCDATA)>
<!ELEMENT Imagen (#PCDATA)>
<!ELEMENT Diagnostico (FechaDiagnostico, RelacionCopaDisco, ResultadoDiagnostico)>
<!ELEMENT FechaDiagnostico (#PCDATA)>
<!ELEMENT RelacionCopaDisco (#PCDATA)>
<!ELEMENT ResultadoDiagnostico (#PCDATA)>

=== ikeramor/pbl_grupo_3/Pagina Web/PBL6.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl"?>
<!--<!DOCTYPE Analisis SYSTEM "PBL6.dtd" []> --> <!--El DTD esta agregado en el archivo PBL6.dtd-->

<Analisis modalidad="Retinografia" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="PBL6.xsd" >
	<Paciente id="1111AAA">
		<Nombre>Ane Miren</Nombre>
		<Apellidos>Garcia de Eulate Martin</Apellidos>
		<Sexo>Mujer</Sexo>
		<Edad>21</Edad>
		<FechaNacimiento>2003-10-02</FechaNacimiento>
		<InformacionDeExtraccion>
			<Especialista>Eider Barrena Diana</Especialista>
			<CentroDeAdquisicion>Txagorritxu</CentroDeAdquisicion>
			<FechaDeAdquisicion>2024-05-06</FechaDeAdquisicion>
		</InformacionDeExtraccion>
		<InformacionDeLaImagen>
			<Bits>4</Bits>
			<ResolucionDeLaImagen>
				<anchura>2468</anchura>
				<altura>2048</altura>
			</ResolucionDeLaImagen>
			<Formato>JPG</Formato>
			<TamañoMB>6</TamañoMB>
			<Imagen></Imagen>
		</InformacionDeLaImagen>
		<Diagnostico>
			<FechaDiagnostico>2024-05-06</FechaDiagnostico>
			<RelacionCopaDisco>0.68</RelacionCopaDisco>
			<ResultadoDiagnostico>Glaucoma</ResultadoDiagnostico>
		</Diagnostico>
	</Paciente>

	<Paciente id="2342BCA">
		<Nombre>Iker</Nombre>
		<Apellidos>Amor Rodriguez</Apellidos>
		<Sexo>Hombre</Sexo>
		<Edad>55</Edad>
		<FechaNacimiento>1969-05-28</FechaNacimiento>
		<InformacionDeExtraccion>
			<Especialista>Javier Blanco Fernandez</Especialista>
			<CentroDeAdquisicion>Cruces</CentroDeAdquisicion>
			<FechaDeAdquisicion>2024-05-08</FechaDeAdquisicion>
		</InformacionDeExtraccion>
		<InformacionDeLaImagen>
			<Bits>4</Bits>
			<ResolucionDeLaImagen>
				<anchura>2468</anchura>
				<altura>2048</altura>
			</ResolucionDeLaImagen>
			<Formato>JPG</Formato>
			<TamañoMB>6</TamañoMB>
			<Imagen></Imagen>
		</InformacionDeLaImagen>
		<Diagnostico>
			<FechaDiagnostico>2023-05-14</FechaDiagnostico>
			<RelacionCopaDisco>0.66</RelacionCopaDisco>
			<ResultadoDiagnostico>Glaucoma</ResultadoDiagnostico>
		</Diagnostico>
	</Paciente>
	
	<Paciente id="8874ZYB">
		<Nombre>Jon Gorka</Nombre>
		<Apellidos>Torres Ramirez</Apellidos>
		<Sexo>Hombre</Sexo>
		<Edad>34</Edad>
		<FechaNacimiento>1990-02-04</FechaNacimiento>
		<InformacionDeExtraccion>
			<Especialista>Ines Diaz Moreno</Especialista>
			<CentroDeAdquisicion>Cruces</CentroDeAdquisicion>
			<FechaDeAdquisicion>2024-05-08</FechaDeAdquisicion>
		</InformacionDeExtraccion>
		<InformacionDeLaImagen>
			<Bits>4</Bits>
			<ResolucionDeLaImagen>
				<anchura>2468</anchura>
				<altura>2048</altura>
			</ResolucionDeLaImagen>
			<Formato>JPG</Formato>
			<TamañoMB>6</TamañoMB>
			<Imagen></Imagen>
		</InformacionDeLaImagen>
		<Diagnostico>
			<FechaDiagnostico>2023-05-14</FechaDiagnostico>
			<RelacionCopaDisco>0.4</RelacionCopaDisco>
			<ResultadoDiagnostico>Sano</ResultadoDiagnostico>
		</Diagnostico>
	</Paciente>
	
	<Paciente id="3489RDF">
		<Nombre>Maite</Nombre>
		<Apellidos>Estibez Oribe</Apellidos>
		<Sexo>Mujer</Sexo>
		<Edad>20</Edad>
		<FechaNacimiento>2004-10-23</FechaNacimiento>
		<InformacionDeExtraccion>
			<Especialista>Luis Martin Martinez</Especialista>
			<CentroDeAdquisicion>Hospital de Gernika</CentroDeAdquisicion>
			<FechaDeAdquisicion>2024-05-08</FechaDeAdquisicion>
		</InformacionDeExtraccion>
		<InformacionDeLaImagen>
			<Bits>4</Bits>
			<ResolucionDeLaImagen>
				<anchura>2468</anchura>
				<altura>2048</altura>
			</ResolucionDeLaImagen>
			<Formato>JPG</Formato>
			<TamañoMB>6</TamañoMB>
			<Imagen></Imagen>
		</InformacionDeLaImagen>
		<Diagnostico>
			<FechaDiagnostico>2023-05-14</FechaDiagnostico>
			<RelacionCopaDisco>0.7</RelacionCopaDisco>
			<ResultadoDiagnostico>Glaucoma</ResultadoDiagnostico>
		</Diagnostico>
	</Paciente>

	<Paciente id="1734ASD">
		<Nombre>Maite</Nombre>
		<Apellidos>Estibez Oribe</Apellidos>
		<Sexo>Mujer</Sexo>
		<Edad>20</Edad>
		<FechaNacimiento>2024-05-07</FechaNacimiento>
		<InformacionDeExtraccion>
			<Especialista>Luis Martin Martinez</Especialista>
			<CentroDeAdquisicion>Galdakaoko Ospitala</CentroDeAdquisicion>
			<FechaDeAdquisicion>2024-05-08</FechaDeAdquisicion>
		</InformacionDeExtraccion>
		<InformacionDeLaImagen>
			<Bits>4</Bits>
			<ResolucionDeLaImagen>
				<anchura>2468</anchura>
				<altura>2048</altura>
			</ResolucionDeLaImagen>
			<Formato>JPG</Formato>
			<TamañoMB>6</TamañoMB>
			<Imagen></Imagen>
		</InformacionDeLaImagen>
		<Diagnostico>
			<FechaDiagnostico>2023-05-14</FechaDiagnostico>
			<RelacionCopaDisco>0.7</RelacionCopaDisco>
			<ResultadoDiagnostico>Glaucoma</ResultadoDiagnostico>
		</Diagnostico>
	</Paciente>
	
	<Paciente id="1734ASD">
		<Nombre>Asier</Nombre>
		<Apellidos>Etxebarria Mugarza</Apellidos>
		<Sexo>Hombre</Sexo>
		<Edad>44</Edad>
		<FechaNacimiento>1980-05-07</FechaNacimiento>
		<InformacionDeExtraccion>
			<Especialista>Urko Aldekoa Aldazabal</Especialista>
			<CentroDeAdquisicion>Cruces</CentroDeAdquisicion>
			<FechaDeAdquisicion>2024-05-08</FechaDeAdquisicion>
		</InformacionDeExtraccion>
		<InformacionDeLaImagen>
			<Bits>4</Bits>
			<ResolucionDeLaImagen>
				<anchura>2468</anchura>
				<altura>2048</altura>
			</ResolucionDeLaImagen>
			<Formato>JPG</Formato>
			<TamañoMB>6</TamañoMB>
			<Imagen></Imagen>
		</InformacionDeLaImagen>
		<Diagnostico>
			<FechaDiagnostico>2023-05-14</FechaDiagnostico>
			<RelacionCopaDisco>0.4</RelacionCopaDisco>
			<ResultadoDiagnostico>Sano</ResultadoDiagnostico>
		</Diagnostico>
	</Paciente>
	
	<Paciente id="1734ASD">
		<Nombre>Izaro</Nombre>
		<Apellidos>Salcines Balinas</Apellidos>
		<Sexo>Mujer</Sexo>
		<Edad>87</Edad>
		<FechaNacimiento>1937-04-27</FechaNacimiento>
		<InformacionDeExtraccion>
			<Especialista>Nerea Velazquez Mendialdua</Especialista>
			<CentroDeAdquisicion>Galdakaoko Ospitala</CentroDeAdquisicion>
			<FechaDeAdquisicion>2024-05-08</FechaDeAdquisicion>
		</InformacionDeExtraccion>
		<InformacionDeLaImagen>
			<Bits>4</Bits>
			<ResolucionDeLaImagen>
				<anchura>2468</anchura>
				<altura>2048</altura>
			</ResolucionDeLaImagen>
			<Formato>JPG</Formato>
			<TamañoMB>6</TamañoMB>
			<Imagen></Imagen>
		</InformacionDeLaImagen>
		<Diagnostico>
			<FechaDiagnostico>2023-05-14</FechaDiagnostico>
			<RelacionCopaDisco>0.8</RelacionCopaDisco>
			<ResultadoDiagnostico>Glaucoma</ResultadoDiagnostico>
		</Diagnostico>
	</Paciente>

</Analisis>
